name: Build and deploy image

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 
      with:
        submodules: true   
    
    - name: Build and push webrandomizer Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tewtal/webrandomizer
        tags: latest    

    - name: Build and push webrandomizer-service Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        dockerfile: Randomizer.Service/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tewtal/webrandomizer-service
        tags: latest    
    
    - name: Deploy to k8s
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: rollout restart deployments/webrandomizer-beta-deployment
