name: Build and deploy image

on:
  push:
    branches: 
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 
      with:
        submodules: true   
    
    - name: Build and push webrandomizer Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tewtal/webrandomizer
        tags: live    

    - name: Build and push webrandomizer-service Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        dockerfile: Randomizer.Service/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tewtal/webrandomizer-service
        tags: live  