name: PR Build with .NET Core 6.0

on:
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100'
    - name: Build and publish with dotnet
      run: dotnet publish --configuration Release
